/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BlikkaMainVPC": {
      "type": "sst.aws.Vpc"
    }
    "BusTargetDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SheetGeneratorDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SheetGeneratorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SubmissionFinalizedBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "UploadFinalizerDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UploadFinalizerQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UploadProcessorDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UploadProcessorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "V2ContactSheetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2MarathonSettingsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2SponsorBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2SubmissionsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2ThumbnailsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2ZipsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ValidationDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ValidationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VotingSmsDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VotingSmsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ZipDownloaderTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "ZipGeneratorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ZipHandlerTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "ZipWorkerDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}