/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BlikkaMainVPC": {
      "type": "sst.aws.Vpc"
    }
    "SheetGeneratorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SubmissionFinalizedBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "UploadFinalizerQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UploadStatusQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "V2ContactSheetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2MarathonSettingsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2SponsorBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2SubmissionsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2ThumbnailsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2ZipsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ValidationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ZipDownloaderCallerFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ZipDownloaderTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "ZipGeneratorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ZipHandlerTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}