-- Photo-archive export state moves from Redis to Postgres. The latest export_jobs row for a
-- marathon is the durable source of truth for the dashboard; chunks are the downloadable archives.

create table if not exists "export_jobs" (
  "id" bigint primary key generated by default as identity,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz,
  "marathon_id" bigint not null,
  "status" text not null,
  "total_chunks" integer not null,
  "completed_chunks" integer not null default 0,
  "failed_chunks" integer not null default 0
);

alter table "export_jobs"
  drop constraint if exists "export_jobs_marathon_id_fkey";

alter table "export_jobs"
  add constraint "export_jobs_marathon_id_fkey"
  foreign key ("marathon_id") references "marathons" ("id") on delete cascade;

create index if not exists "export_jobs_marathon_id_idx"
  on "export_jobs" ("marathon_id");

-- DB-enforced "one in-flight export per marathon" — replaces the Redis active-pointer guard.
create unique index if not exists "export_jobs_one_processing_per_marathon_key"
  on "export_jobs" ("marathon_id")
  where "status" = 'processing';

create table if not exists "export_job_chunks" (
  "id" bigint primary key generated by default as identity,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz,
  "export_job_id" bigint not null,
  "competition_class_id" bigint not null,
  "competition_class_name" text not null,
  "min_reference" integer not null,
  "max_reference" integer not null,
  "zip_key" text not null,
  "status" text not null,
  "chunk_index" integer not null,
  "class_total_chunks" integer not null
);

alter table "export_job_chunks"
  drop constraint if exists "export_job_chunks_export_job_id_fkey";

alter table "export_job_chunks"
  add constraint "export_job_chunks_export_job_id_fkey"
  foreign key ("export_job_id") references "export_jobs" ("id") on delete cascade;

create index if not exists "export_job_chunks_export_job_id_idx"
  on "export_job_chunks" ("export_job_id");
