create table if not exists "gallery_publications" (
  "id" bigint primary key generated by default as identity,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz,
  "marathon_id" bigint not null,
  "topic_id" bigint,
  "published_at" timestamptz,
  "featured_sections" jsonb not null default '[]'::jsonb
);

alter table "gallery_publications"
  drop constraint if exists "gallery_publications_marathon_id_fkey";

alter table "gallery_publications"
  add constraint "gallery_publications_marathon_id_fkey"
  foreign key ("marathon_id") references "marathons" ("id") on delete cascade;

alter table "gallery_publications"
  drop constraint if exists "gallery_publications_topic_id_fkey";

alter table "gallery_publications"
  add constraint "gallery_publications_topic_id_fkey"
  foreign key ("topic_id") references "topics" ("id") on delete cascade;

create index if not exists "gallery_publications_marathon_id_idx"
  on "gallery_publications" ("marathon_id");

create unique index if not exists "gallery_publications_marathon_topic_key"
  on "gallery_publications" ("marathon_id", coalesce("topic_id", 0));

-- Supporting indexes for the public gallery query shapes.
create index if not exists "participants_domain_status_idx"
  on "participants" ("domain", "status");

create index if not exists "submissions_marathon_topic_status_idx"
  on "submissions" ("marathon_id", "topic_id", "status");

create index if not exists "topics_marathon_order_idx"
  on "topics" ("marathon_id", "order_index");
