-- Jury reviews move from an ordered 1-2-3 podium to an unordered shortlist of favorites, with a
-- single winner picked from that shortlist. The winner lives on the shortlist row itself, so
-- "the winner is one of the picks" is structural rather than an application-level cross-check.

create table if not exists "jury_shortlist_picks" (
  "id" bigint primary key generated by default as identity,
  "created_at" timestamptz not null default now(),
  "invitation_id" bigint not null,
  "participant_id" bigint not null,
  "marathon_id" bigint not null,
  "is_winner" boolean not null default false
);

alter table "jury_shortlist_picks"
  drop constraint if exists "jury_shortlist_picks_invitation_id_fkey";

alter table "jury_shortlist_picks"
  add constraint "jury_shortlist_picks_invitation_id_fkey"
  foreign key ("invitation_id") references "jury_invitations" ("id") on delete cascade;

alter table "jury_shortlist_picks"
  drop constraint if exists "jury_shortlist_picks_marathon_id_fkey";

alter table "jury_shortlist_picks"
  add constraint "jury_shortlist_picks_marathon_id_fkey"
  foreign key ("marathon_id") references "marathons" ("id") on delete cascade;

alter table "jury_shortlist_picks"
  drop constraint if exists "jury_shortlist_picks_participant_id_fkey";

alter table "jury_shortlist_picks"
  add constraint "jury_shortlist_picks_participant_id_fkey"
  foreign key ("participant_id") references "participants" ("id") on delete cascade;

alter table "jury_shortlist_picks"
  drop constraint if exists "jury_shortlist_picks_invitation_participant_key";

alter table "jury_shortlist_picks"
  add constraint "jury_shortlist_picks_invitation_participant_key"
  unique ("invitation_id", "participant_id");

-- DB-enforced "at most one winner per invitation".
create unique index if not exists "jury_shortlist_picks_invitation_winner_key"
  on "jury_shortlist_picks" ("invitation_id")
  where "is_winner";

create index if not exists "jury_shortlist_picks_invitation_id_idx"
  on "jury_shortlist_picks" ("invitation_id");

create index if not exists "jury_shortlist_picks_participant_id_idx"
  on "jury_shortlist_picks" ("participant_id");

create index if not exists "jury_shortlist_picks_marathon_id_idx"
  on "jury_shortlist_picks" ("marathon_id");

-- Carry existing podiums over: all three ranked picks become shortlist entries, and the old
-- 1st place becomes the winner. Reviews already marked completed keep that status; completion is
-- only ever evaluated at the moment a juror submits.
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'jury_final_rankings'
  ) then
    insert into "jury_shortlist_picks"
      ("created_at", "invitation_id", "participant_id", "marathon_id", "is_winner")
    select "created_at", "invitation_id", "participant_id", "marathon_id", "rank" = 1
    from "jury_final_rankings"
    on conflict ("invitation_id", "participant_id") do nothing;
  end if;
end $$;

drop table if exists "jury_final_rankings";
