-- Normalize duplicate tokens generated by legacy bulk voting-session creation.
WITH duplicate_tokens AS (
  SELECT
    id,
    token,
    row_number() OVER (PARTITION BY token ORDER BY id) AS rn
  FROM voting_session
)
UPDATE voting_session AS vs
SET
  token = substring(md5(vs.token || ':' || vs.id::text || ':' || clock_timestamp()::text) for 16),
  updated_at = now()
FROM duplicate_tokens AS dt
WHERE vs.id = dt.id
  AND dt.rn > 1;

DROP INDEX IF EXISTS voting_session_connected_participant_id_unique_idx;

CREATE UNIQUE INDEX IF NOT EXISTS voting_session_connected_participant_topic_unique_idx
  ON voting_session (connected_participant_id, topic_id);

CREATE UNIQUE INDEX IF NOT EXISTS voting_session_token_unique_idx
  ON voting_session (token);

CREATE INDEX IF NOT EXISTS voting_session_marathon_topic_idx
  ON voting_session (marathon_id, topic_id);
